Doc: Fixed broken links, plus more conversion to markdown.
ARM-software/CMSIS-RTX pull request #8
Opened 2023-10-20 13:29 UTC by vovamarch

2023-10-23 05:27 UTC, RobertRostohar requested changes
Formatting of Exercise 2- 6 in Tutorial documentation seems to be broken.

There are also still some broken doc links reported by check_links.sh:
Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/runner/work/CMSIS-RTX/CMSIS-RTX/CMSIS/Documentation/html/namespace_3globalScope_4.html'>
Error: 404 Not Found  https://arm-software.github.io/CMSIS_6/main/RTOS2/html/namespace_3globalScope_4.html#group__CMSIS__RTOS__TimerMgmt
Error: 404 Not Found https://arm-software.github.io/CMSIS_6/main/Core/html/namespace_3globalScope_4.html#structSCB__Type

2023-10-23 07:21 UTC, JonatanAntoni approved these changes

2023-10-23 08:30 UTC, vovamarch commented
@RobertRostohar , unfortunately I can't get the links to structures osXXXAttr_t working. Doxygen doesn't resolve the links correctly, that's why 404 on those. Suggest to raise as a known issue for now.

2023-10-25 09:47 UTC, RobertRostohar approved these changes

2023-10-25 09:49 UTC, merged